backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: dksw77ej0
    api_key: 381242588879478
    default_transformations:
      - - fetch_format: auto
          width: 420
          quality: auto
          crop: scale

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: "SEO image"
            name: seoImage
            widget: image
            media_library:
              config:
                multiple: false
          - label: "Blocks"
            name: "blocks"
            widget: list
            types:
              - label: "Archive Button"
                name: "archive-button"
                widget: string
                default: ""
                required: false
              - label: "Empty Block"
                name: "empty-block"
                widget: object
                summary: "{{fields.columns}} x {{fields.rows}}"
                fields:
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
                  - label: Border
                    name: border
                    widget: boolean
                    default: true
              - label: "Content Block"
                name: "content-block"
                widget: object
                summary: "{{fields.label}}"
                fields:
                  - label: Label
                    name: label
                    widget: string
                    required: false
                    default: ""
                  - label: Slug
                    name: slug
                    widget: string
                    required: false
                  - label: Description
                    name: description
                    widget: string
                    required: false
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
                  - label: Open
                    name: open
                    widget: boolean
                    default: false
                  - label: Border
                    name: border
                    widget: boolean
                    default: true
                  - label: Body
                    name: body
                    widget: markdown
                  - label: "Bottom images"
                    name: bottom-images
                    widget: image
                    required: false
                    media_library:
                      config:
                        multiple: true
              - label: "Image Block"
                name: "image-block"
                widget: object
                summary: "{{fields.description}}"
                fields:
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
                  - label: Border
                    name: border
                    widget: boolean
                    default: true
                  - label: Description
                    name: description
                    widget: string
                  - label: "Image"
                    name: image
                    widget: image
                    media_library:
                      config:
                        multiple: false
                  - label: "Link"
                    name: link
                    required: false
                    widget: string
              - label: "Gradient Block"
                name: "gradient-block"
                widget: object
                summary: "{{fields.columns}} x {{fields.rows}} {{ fields.color1 }} {{ fields.color2 }}"
                fields:
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
                  - label: Border
                    name: border
                    widget: boolean
                    default: true
                  - label: "Color 1"
                    name: color1
                    widget: color
                    default: "#c1a2f2"
                    allowInput: true
                  - label: "Color 2"
                    name: color2
                    widget: color
                    default: "#ffc540"
                    allowInput: true
              - label: "Text Block"
                name: "text-block"
                widget: object
                summary: "{{fields.text }}"
                fields:
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
                  - label: Border
                    name: border
                    widget: boolean
                    default: true
                  - label: Text
                    name: text
                    widget: string
          - label: "Archive"
            name: "archive"
            widget: list
            types:
              - label: "Archive Block"
                name: "archive-block"
                widget: object
                summary: "{{fields.label}}"
                fields:
                  - label: Label
                    name: label
                    widget: string
                    required: false
                    default: ""
                  - label: Body
                    name: body
                    widget: markdown
