backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: dksw77ej0
    api_key: 381242588879478

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: Title
            name: title
            widget: string
          - label: Heading
            name: heading
            widget: string
          - label: Subheading
            name: subheading
            widget: string
          - label: Description
            name: description
            widget: string
          - label: "Blocks"
            name: "blocks"
            widget: list
            types:
              - label: "Empty Block"
                name: "empty-block"
                widget: object
                summary: "{{fields.columns}} x {{fields.rows}} {{ fields.round }}"
                fields:
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
              - label: "Content Block"
                name: "content-block"
                widget: object
                summary: "{{fields.label}}"
                fields:
                  - label: Label
                    name: label
                    widget: string
                    default: ""
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
                  - label: Body
                    name: body
                    widget: markdown
                  - label: "Bottom images"
                    name: bottom-images
                    widget: image
                    media_library:
                      config:
                        multiple: true
              - label: "Image Block"
                name: "image-block"
                widget: object
                summary: "{{fields.image}}"
                fields:
                  - label: Columns
                    name: columns
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Rows
                    name: rows
                    widget: select
                    options:
                      - { label: "1", value: 1 }
                      - { label: "2", value: 2 }
                      - { label: "3", value: 3 }
                      - { label: "4", value: 4 }
                    default: 1
                  - label: Round
                    name: round
                    widget: boolean
                    default: false
                  - label: Border
                    name: border
                    widget: boolean
                    default: true
                  - label: "Image"
                    name: image
                    widget: image
                    media_library:
                      config:
                        multiple: false
